language: generic 
sudo: required
services:
 - docker

before-install:
 - docker build -t sankethns/docker-react -f Dockerfile.dev .

script:
 - docker run sankethns/docker-react npm run test -- --coverage
